### ISSUE TITLE
Understand settings work

### ISSUE THREAD

**Issue by VasterLordEP** [AbroGames/NeonWarfare#15]
Нужно разобраться, куда создавать настройки (сейчас настройки игрока создаются в папке users, нужно в какую-то свою). 
Не кидать ошибку при первом создании настроек.

**Comment by Bronuh** [comment]
А почему не в папке Users? Как я понимаю, `user://` создано для чтения и записи файлов в место с гарантированным доступом у пользователя. Это нормальный подход, а что б не искать потом эту папку можно просто куда-нибудь добавить кнопку "Открыть папку с данными игры" или чет такое

**Comment by Bronuh** [comment]
`user://` ведет куда-то по пути `/home/<username>/.local/share/<engine>/app_userdata/<game>/` в линуксах и `C:/Users/<username>/AppData/Roaming/<engine>/app_userdata/<game>/` в винде
