### ISSUE TITLE
Move link to FloatingLabel in ScreenPackedSceneContainer

### ISSUE THREAD

**Issue by KeyJ148** [AbroGames/NeonWarfare#19]
Или оставить на месте, т.к. FloatingLabel и так привязан к сетке мира? Но лучше в EffectsPackedScenesContainer тогда вынести, или типа того
Scenes/PackedScenesContainer/Client/World/ClientWorldPackedScenesContainer.cs:11

**Comment by KeyJ148** [comment]
@Bronuh @VasterLordEP 
FloatingLabel куда лучше вынести? Оставить в World / Вынести в Screen / Вынести в Effects?
Это надпись на экране при попадании по врагу, например. Привязана к сетке мира.

**Comment by Bronuh** [comment]
Ну, оно находится в игровом мире, но не взаимодействует с ним, можно в Effects выкинуть наверное
